config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'
  root 'statice_pages#home'
  get '/help', to: 'statice_pages#help'
  get '/about', to: 'statice_pages#about'
  get '/contact', to:'statice_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: :new
  resources :tweets, only: %i(index create destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
   validates :user_id, presence: true
   validates :content, presence: true, length: { maximum: 140 } 
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , length:{maximum: 50}
  validates :email, presence: true , length:{maximum: 255}
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'ログインしてください'
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.name == params[:session][:name]
      login(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'nameまたはemailが正しくありません'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

end

app/controllers/statice_pages_controller.rb
class StaticePagesController < ApplicationController
  def contact
  end

  def home
     @tweet = current_user.tweets.build if logged_in?
     @tweets = Tweet.paginate(page: params[:page]).order(created_at: :desc)
   end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @tweets = Tweet.paginate(page: params[:page]).order(created_at: :desc)
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = 'つぶやきました'
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    flash[:success] = "削除しました"
    redirect_to root_url
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i(edit update destroy)
  before_action :correct_user, only: %i(edit update destroy)

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(page: params[:page]).order(created_at: :desc)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = '登録ありがとうございます'
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'プロフィールを更新しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "退会処理をしました"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url)unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title ='')
    base_title = "TweetApp"
    if page_title.empty?
      base_title
    else
      page_title + '|' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    current_user.present?
  end
  
   def redirect_back_or(default)
     redirect_to(session[:forwarding_url] || default)
     session.delete(:forwarding_url)
   end

   def store_location
     session[:forwarding_url] = request.original_url if request.get?
   end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/statice_pages_helper.rb
module StaticePagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_contact.html.erb
 <% provide(:title, 'Contact') %>
 <h2>Contact</h2>

app/views/layouts/_footer.html.erb
  <footer class="footer">
      <nav>
        <ul>
          <li><%= link_to('Home', root_path) %></li>
          <li><%= link_to('Help', help_path) %></li>
          <li><%= link_to('About', about_path) %></li>
          <li><%= link_to('Contact', contact_path) %></li>
        </ul>
      </nav>
  </footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to('TweetApp', root_path, class: 'logo') %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Home', root_path) %></li>
             <li><%= link_to('全てのtweet', tweets_path) %></li>
             <li><%= link_to "Users", users_path %></li>
            <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
            </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/ html5.min.js"></script>
  <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert <%= "alert-#{message_type}" %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>




  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
   <div class="alert alert-danger">
     <%= object.errors.count %>つのエラーが確認できました
   </div>
   <ul>
     <% object.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_tweet_form.html.erb
<%= form_with(model: @tweet, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "今の思いをつぶやこう" %>
    </div>
    <%= f.submit "つぶやく", class: "btn btn-primary" %>
  <% end %>

app/views/statice_pages/about.html.erb
<% provide(:title, 'About') %>
<h2>About</h2>
<p>This is About page og TweetApp</p>

app/views/statice_pages/contact.html.erb
 <% provide(:title, 'Contact') %>
 <h2>Contact</h2>

app/views/statice_pages/help.html.erb
<% provide(:title, 'Help') %>
<h2>Help</h2>
<p>This is Help page of TweetApp</p>

app/views/statice_pages/home.html.erb
 <% if logged_in? %>
 <div class="row">
   <aside class="col-md-4">
     <section class="user-info">
       <h2><%= current_user.name %></h2>
       <span><%= link_to "view my profile", current_user %></span>
       <span><%= pluralize(current_user.tweets.count, "tweet") %></span>
     </section>
     <section class="tweet-form"><%= render 'shared/tweet_form' %></section>
   </aside>
 <div class="col-md-8">
   <h2>tweets</h2>
    <ol class="tweets"><%= render @tweets %></ol>
    <%= will_paginate @tweets %>
  </div>
 <% else %>
 <div class="center jumbotron">
  <h2 class="welcom-message">Welcom to the TweetApp</h2>
  <%= link_to 'Sign up now!', 'signup', class: "btn btn-lg btn-primary sign-up" %>
  </div>
</div>
<% end %>

app/views/tweets/_tweet.html.erb
<li id="tweet-<%= tweet.id %>">
  <span class="user"><%= link_to tweet.user.name, tweet.user %></span>
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
  </span>
  <span><%= link_to('削除', tweet, method: :delete) %></span>
</li>

app/views/tweets/index.html.erb
 <%provide(:title,'AllTweets')%>
 <h2>全てのtweet</h2>
 <section class="all-tweets">
   <ol class="tweets">
     <%= render @tweets %>
   </ol>
   <%= will_paginate %>
 </section>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render('shared/error_messages',object: f.object) %>
  <%= f.label(:name)%>
  <%= f.text_field(:name, class: 'form-control')%>
  <%= f.label(:email)%>
  <%= f.email_field(:email, class: 'form-control')%>
  <%= f.submit(button, class:"btn btn-primary")%>
<% end %>

app/views/users/edit.html.erb
 <% provide(:title, "アップデート") %>
 <h2>プロフィールのアップデート</h2>
 <div class="row">
   <div class="col-md-6 col-md-offset-3">
     <%= render 'users/form', {user: @user, button:'更新する'}%>
   </div>
 </div>

app/views/users/index.html.erb
<% provide(:title, 'すべてのユーザー') %>
<h2>全ユーザー</h2>
  <ul class="users">
    <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up')%>
<h2>ユーザー登録</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form', {user: @user, button:'アカウント登録' }%>
     <p>新しいユーザーの方は<%= link_to "ユーザー登録", signup_path %></p>
  </div>
</div>

app/views/users/show.html.erb
 <% provide(:title, @user.name) %>
 <div class="row">
   <aside class="col-md-4">
     <section class="user_info">
       <h2><%= @user.name %></h2>
       <% if current_user?(@user) %>
        <p><%= link_to('プロフィール編集',edit_user_path(@user)) %></p>
        <p><%= link_to('退会', @user, method: :delete, data:{confirm: "よろしいですか？" }) %></p>
        <% end %>
     </section>
   </aside>
   <div class="col-md-8">
     <% if @user.tweets.any? %>
     <h2>tweets (<%= @user.tweets.count %>)</h2>
      <ol class="tweets">
        <%= render @tweets %>
      </ol>
      <%= will_paginate @tweets %>
      <% end %>
    </div>
 </div>